easy_admin:
    site_name: 'Eco-Service Back Office'
    entities:
        Product :
            class: App\Entity\Product
        Category :
            class: App\Entity\Category
        User :
            class: App\Entity\User
        Article:
            class: App\Entity\Article
        Service :
            class: App\Entity\Service
        Subject :
            class: App\Entity\Subject
        Unity :
            class: App\Entity\Unity
        Company :
            class: App\Entity\Company
        Quotation :
            class: App\Entity\Quotation
        Bill :
            class: App\Entity\Bill
