knp_paginator:
  page_range: 5
  default_options:
    page_name: page_name
    sort_field_name: sort
    sort_direction_name: direction
    distinct: true
    filter_field_name: filterfield
    filter_value_name: filtervalue
  template:
    #pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'
    sortable: 'pagination/sortable.html.twig'
    #filtration: '@KnpPaginator/Pagination/filtration.html.twig'
