vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix:         '%app.path.product_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.product_images%'
#        bill_invoices:
#            uri_prefix: '%app.path.bill_invoices%'
#            upload_destination: '%kernel.project_dir%/public%app.path.bill_invoices%'


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/produits'
