easy_admin:
  site_name: "<a href='http://127.0.0.1:8000'>Eco-Service</a>"
  design:
    brand_color: 'white'
    assets:
      css:
        - 'css/custom_backend.css'
  list:
    actions:
      - { name: 'edit', icon: 'pencil', label: false }
      - { name: 'delete', icon: 'remove', label: false }
      - { name: 'search', label: 'Recherche...'}
