easy_admin:
  site_name: '<img src="">Eco-Service'
  design:
    brand_color: '#81b9ba'
    assets:
      css:
        - 'css/custom_backend.css'
  list:
    actions:
      - { name: 'edit', icon: 'pencil', label: false }
      - { name: 'delete', icon: 'remove', label: false }
      - { name: 'search', label: 'Recherche...'}
