easy_admin:
  site_name: 'Eco-Service <em style="font-size:80%">Back Office</em>'
  design:
    brand_color: '#81b9ba'
    assets:
      css:
        - 'css/custom_backend.css'
  list:
    actions:
      - { name: 'edit', icon: 'pencil', label: false }
      - { name: 'delete', icon: 'remove', label: false }