easy_admin:
  design:
    menu:
      - label: Dashboard
        icon: 'home'
        route: admin_dashboard
        default: true
      - label: Produits
        icon: 'shopping-basket'
        children:
          - {entity: 'Product', icon: 'th-list', label: 'Liste des produits'}
          - {entity: 'Category', icon: 'tags', label: 'Catégories'}
          - { entity: 'Product', icon: 'plus-circle', label: 'Ajouter un produit', params: { action: 'new' } }
      - label: Services
        icon: 'newspaper-o'
        children:
          - {entity: 'Service', icon: 'newspaper-o', label: 'Liste des services'}
      - label: Membres
        icon: 'user-circle-o'
        children:
          - {entity: 'User', icon: 'th-list', label: 'Liste des membres'}
      - label: Devis
        icon: 'file-text-o'
        children:
          - {entity: 'Bill', icon: 'th-list', label: 'Liste des devis'}
      - label: Newsletters
        icon: 'info-circle'
        children:
          - {entity: 'Newsletter', icon: 'th-list', label: 'Liste des newsletters'}
      - label: Messages
        icon: 'comment'
        children:
          - {entity: 'Message', icon: 'th-list', label: 'Liste des messages'}
      - label: Images
        icon: 'file-text-o'
        children:
          - {entity: 'File', icon: 'th-list', label: 'Liste des images'}
      - label: Articles
        icon: 'newspaper-o'
        children:
          - {entity: 'Article', icon: 'th-list', label: 'Liste des articles'}

