easy_admin:
  list:
    title: 'Liste des %%entity_label%%'
  edit:
    title: 'Editer lArticle %%entity_id%%'
  new:
    title: 'Ajouter un Article'
  entities:
    Article:
      class: App\Entity\Article
      label: 'Articles'
      list:
        actions:
          - { name: 'new', label: 'Ajouter un Article '}
        fields:
          - { property: 'author', label: 'Auteur' }
          - { property: 'category', label: 'Categorie' }
          - { property: 'name', label: 'Nom' }
          - { property: 'slug', label: 'Slug' }
          - { property: 'content', label: 'Contenu'}
      form:
        actions:
          - { name: 'delete', label: 'Supprimer' }
        fields:
          - { property: 'author', label: 'Auteur' }
          - { property: 'category', label: 'Categorie' }
          - { property: 'name', label: 'Nom' }
          - { property: 'slug', label: 'Slug' }
          - { property: 'content', label: 'Contenu'}
        disabled_actions: ['edit']
