easy_admin:
  list:
    title: 'Liste des %%entity_label%%'
  entities:
    File:
      class: App\Entity\File
      label: 'Images'
      list:
        fields:
          - { property: 'name', label: 'Nom' }
          - { property: 'uri', label: 'Liens' }
          - { property: 'orderFile', label: 'Ordre' }
          - { property: 'alt_file', label: 'Description' }
      form:
        fields:
        - { property: 'name', label: 'Nom' }
        - { property: 'orderFile', label: 'Ordre', type: 'number' }
        - { property: 'alt_file', label: 'Description' }
