easy_admin:
  list:
    title: 'Liste des %%entity_label%%'
  edit:
    title: 'Editer une Image %%entity_id%%'
  new:
    title: 'Ajouter une Image'
  entities:
    File:
      class: App\Entity\File
      label: 'Images'
      list:
        actions:
          - { name: 'new', label: 'Ajouter une Image'}
        fields:
          - { property: 'name', label: 'Nom' }
          - { property: 'uri', label: 'Liens' }
          - { property: 'orderFile', label: 'Ordre' }
          - { property: 'alt_file', label: 'Description' }
      form:
        actions:
          - { name: 'delete', label: 'Supprimer' }
        fields:
          - { property: 'name', label: 'Nom' }
          - { property: 'uri', label: 'Lien' }
          - { property: 'orderFile', label: 'Ordre', type: 'number' }
          - { property: 'alt_file', label: 'Description' }
        disabled_actions: ['edit']
