easy_admin:
  design:
    form_theme:
      - '@EasyAdmin/form/bootstrap_4.html.twig'
      - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
  edit:
    title: 'Editer une Image (#%%entity_id%%)'
  list:
    title: 'Liste des %%entity_label%%'
  new:
    title: 'Ajouter une Image'
  entities:
    File:
      class: App\Entity\File
      label: 'Images'
      list:
        actions:
          - { name: 'new', label: 'Ajouter une Image'}
        fields:
          - { property: 'name', label: 'Nom' }
          - { property: 'uri', label: 'Liens' }
          - { property: 'orderFile', label: 'Ordre' }
          - { property: 'alt_file', label: 'Description' }
      form:
        actions:
          - { name: 'delete', label: 'Supprimer' }
          - { name: 'list', label: 'Retourner vers la liste' }
        fields:
          - { property: 'name', label: 'Nom' }
          - { property: 'uri', label: 'Lien' }
          - { property: 'orderFile', label: 'Ordre', type: 'number' }
          - { property: 'alt_file', label: 'Description', type: 'fos_ckeditor' }
        disabled_actions: ['edit']
