easy_admin:
  list:
    title: 'Liste des %%entity_label%%'
  entities:
    User:
      class: App\Entity\User
      label: 'Membres'
      list:
        actions:
          - { name: 'new', label: 'Ajouter un Utilisateur '}
        fields:
        - { property: 'email', label: 'Mail' }
        - { property: 'firstName', label: 'Prénom' }
        - { property: 'lastName', label: 'Nom' }
        - { property: 'phone', label: 'Téléphone' }
        - { property: 'newsletterAcceptance', label: 'Newsletter', type: 'toggle'}
      form:
        fields:
        - { property: 'delivery_address', label: 'Adresse de livraison' }
        - { property: 'billing_address', label: 'Address du devis' }
        - { property: 'email', label: 'Mail', type: 'email' }
        - { property: 'firstName', label: 'Prénom' }
        - { property: 'lastName', label: 'Nom' }
        - { property: 'phone', label: 'Téléphone', type: 'tel' }
        - { property: 'newsletterAcceptance', label: 'Newsletter',  type: 'checkbox' }
