easy_admin:
  design:
    form_theme:
      - '@EasyAdmin/form/bootstrap_4.html.twig'
      - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
  list:
    title: 'Liste des %%entity_label%%'
  entities:
    Message:
      class: App\Entity\Message
      edit:
        title: 'Editer le Message (#%%entity_id%%)'
      new:
        title: 'Ajouter un Message'
      disabled_actions: ['new', 'edit']
      label: 'Messages'
      list:
        actions:
          - { name: 'show', icon: 'search', label: false}
        fields:
          - { property: 'email', label: 'Email' }
          - { property: 'firstName', label: 'Prénom' }
          - { property: 'lastName', label: 'Nom' }
          - { property: 'subject', label: 'Sujet' }
      show:
        title: 'Message (#%%entity_id%%)'
        actions:
          - { name: 'delete', label: 'Supprimer' }
          - { name: 'list', label: 'Retourner vers la liste' }
        fields:
          - { property: 'email', label: 'Email' }
          - { property: 'firstName', label: 'Prénom' }
          - { property: 'lastName', label: 'Nom' }
          - { property: 'subject', label: 'Sujet' }
          - { property: 'content', label: 'Contenu', type: 'fos_ckeditor' }
        disabled_actions: ['edit']
