easy_admin:
  design:
    form_theme:
      - '@EasyAdmin/form/bootstrap_4.html.twig'
      - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
  list:
    title: 'Liste des %%entity_label%%'
  edit:
    title: 'Editer le Message (#%%entity_id%%)'
  new:
    title: 'Ajouter un Message'
  entities:
    Message:
      class: App\Entity\Message
      label: 'Messages'
      list:
        actions:
          - { name: 'new', label: 'Ajouter un Message '}
        fields:
        - { property: 'state', label: 'Etat' }
        - { property: 'content', label: 'Contenu' }
        - { property: 'subject', label: 'Sujet' }
        - { property: 'author', label: 'Auteur' }
      form:
        actions:
          - { name: 'delete', label: 'Supprimer' }
        fields:
          - { property: 'state', label: 'Etat' }
          - { property: 'content', label: 'Contenu', type: 'fos_ckeditor' }
          - { property: 'subject', label: 'Sujet' }
          - { property: 'author', label: 'Auteur' }
        disabled_actions: ['edit']
