easy_admin:
  list:
    title: 'Liste des %%entity_label%%'
  entities:
    Message:
      class: App\Entity\Message
      label: 'Messages'
      list:
        actions:
          - { name: 'new', label: 'Ajouter un Message '}
        fields:
        - { property: 'state', label: 'Etat' }
        - { property: 'content', label: 'Contenu' }
        - { property: 'subject', label: 'Sujet' }
        - { property: 'author', label: 'Auteur' }
      form:
        actions:
          - { name: 'edit', label: 'Modifier' }
          - { name: 'delete', label: 'Supprimer' }
        fields:
        - { property: 'state', label: 'Etat' }
        - { property: 'content', label: 'Contenu' }
        - { property: 'subject', label: 'Sujet' }
        - { property: 'author', label: 'Auteur' }
