easy_admin:
  list:
    title: 'Liste des %%entity_label%%'
  entities:
    Newsletter:
      class: App\Entity\Newsletter
      label: 'Newsletters'
      list:
        fields:
        - { property: 'subject', label: 'Sujet' }
        - { property: 'content', label: 'Contenu' }
        - { property: 'author', label: 'Auteur' }
      form:
        fields:
        - { property: 'subject', label: 'Sujet' }
        - { property: 'content', label: 'Contenu' }
        - { property: 'author', label: 'Auteur' }

