easy_admin:
  list:
    title: 'Liste des %%entity_label%%'
  entities:
    Newsletter:
      class: App\Entity\Newsletter
      label: 'Newsletters'
      list:
        actions:
          - { name: 'new', label: 'Ajouter une Newsletter '}
        fields:
        - { property: 'subject', label: 'Sujet' }
        - { property: 'content', label: 'Contenu' }
        - { property: 'author', label: 'Auteur' }
      form:
        actions:
          - { name: 'delete', label: 'Supprimer' }
        fields:
          - { property: 'subject', label: 'Sujet' }
          - { property: 'content', label: 'Contenu' }
          - { property: 'author', label: 'Auteur' }
        disabled_actions: ['edit']

