easy_admin:
  list:
    title: 'Liste des %%entity_label%%'
  entities:
    Quotation:
      disabled_actions: ['new']
      class: App\Entity\Quotation
      edit:
        title: 'Modifier la Facture (#%%entity_id%%)'
      label: 'Facture'
      list:
        actions:
          - { name: 'show', icon: 'search', label: false }
        fields:
          - { property: 'request_date', label: 'Date de demande' }
          - { property: 'approved', label: 'Approuvé' }
          - { property: 'company_id', label: 'Entreprise' }
          - { property: 'acceptance_date', label: 'Date de confirmation' }
          - { property: 'email', label: 'Mail' }
          - { property: 'billing_address', label: 'Adresse du devis'}
          - { property: 'delivery_address', label: 'Adresse de livraison'}
      form:
        actions:
          - { name: 'delete', label: 'Supprimer' }
          - { name: 'list', label: 'Retourner vers la liste' }
        fields:
          - { property: 'request_date', label: 'Date de demande' }
          - { property: 'company_id', label: 'Entreprise' }
          - { property: 'approved', label: 'Approuvé' }
          - { property: 'acceptance_date', label: 'Date de confirmation' }
          - { property: 'email', label: 'Mail' }
          - { property: 'billing_address', label: 'Adresse du devis' }
          - { property: 'delivery_address', label: 'Adresse de livraison' }
        disabled_actions: ['edit']
      show:
        title: 'Facture (#%%entity_id%%)'
        actions:
          - { name: 'delete', label: 'Supprimer' }
          - { name: 'edit', label: 'Modifier' }
          - { name: 'list', label: 'Retourner vers la liste' }
        fields:
          - { property: 'request_date', label: 'Date de demande', type: 'date' }
          - { property: 'approved', label: 'Approuvé' }
          - { property: 'company_id', label: 'Entreprise' }
          - { property: 'acceptance_date', label: 'Date de confirmation', type: 'date' }
          - { property: 'email', label: 'Mail' }
          - { property: 'billing_address', label: 'Adresse du devis'}
          - { property: 'delivery_address', label: 'Adresse de livraison'}
