easy_admin:
  design:
    form_theme:
      - '@EasyAdmin/form/bootstrap_4.html.twig'
      - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
  list:
    title: 'Liste des %%entity_label%%'
  entities:
    Service:
      edit:
        title: 'Editer le Service (#%%entity_id%%)'
      new:
        title: 'Ajouter un Service'
      class: App\Entity\Service
      label: 'Services'
      list:
        actions:
          - { name: 'new', label: 'Ajouter un Service '}
        fields:
          - { property: 'name', label: 'Nom' }
          - { property: 'priceHt', label: 'Prix HT' }
          - { property: 'priceTtc', label: 'Prix TTC' }
          - { property: 'author', label: 'Auteur' }
          - { property: 'content', label: 'Contenu' }
          - { property: 'unity', label: 'Unité' }
          - { property: 'author', label: 'Auteur' }
          - { property: 'images', label: 'Images'}
      form:
        actions:
          - { name: 'delete', label: 'Supprimer' }
          - { name: 'list', label: 'Retourner vers la liste' }
        fields:
          - { property: 'name', label: 'Nom'}
          - { property: 'priceHt', label: 'Prix HT', type: 'number' }
          - { property: 'priceTtc', label: 'Prix TTC', type: 'number' }
          - { property: 'content', label: 'Contenu', type: 'fos_ckeditor' }
          - { property: 'author', label: 'Auteur' }
          - { property: 'unity', label: 'Unité' }
          - { property: 'images', label: 'Images'}
        disabled_actions: ['edit']
