easy_admin:
  list:
    title: 'Liste des unités'
  entities:
    Unity:
      class: App\Entity\Unity
      edit:
        title: 'Editer une unité (#%%entity_label%%)'
      new:
        title: 'Ajouter une unité'
      label: 'Unités'
      list:
        actions:
          - { name: 'show', icon: 'search', label: false }
          - { name: 'new', label: 'Ajouter une unité '}
        fields:
          - { property: 'name', label: 'Nom' }
      form:
        actions:
          - { name: 'delete', label: 'Supprimer' }
          - { name: 'list', label: 'Retourner vers la liste' }
        fields:
          - { property: 'name', label: 'Nom' }
        disabled_actions: ['edit']
