#index
index:
    path: /
    controller: App\Controller\UserController::initialisation
    methods: [GET, POST]


#cafetiere
cafetiere_index:
    path: /cafetiere
    controller: App\Controller\CafetiereController::index
    methods: [GET]

cafetiere_new:
    path: /cafetiere/new/
    controller: App\Controller\CafetiereController::new
    methods: [GET, POST]

cafetiere_show:
    path: /cafetiere/show/{id}
    controller: App\Controller\CafetiereController::show
    methods: [GET]

cafetiere_edit:
    path: /cafetiere/edit/{id}
    controller: App\Controller\CafetiereController::edit
    methods: [GET, POST]

cafetiere_delete:
    path: /cafetiere/delete/{id}
    controller: App\Controller\CafetiereController::delete
    methods: [DELETE]


#cannon
cannon_index:
    path: /cannon
    controller: App\Controller\CannonController::index
    methods: [GET]

cannon_new:
    path: /cannon/new/
    controller: App\Controller\CannonController::new
    methods: [GET, POST]

cannon_show:
    path: /cannon/show/{id}
    controller: App\Controller\CannonController::show
    methods: [GET]

cannon_edit:
    path: /cannon/edit/{id}
    controller: App\Controller\CannonController::edit
    methods: [GET, POST]

cannon_delete:
    path: /cannon/delete/{id}
    controller: App\Controller\CannonController::delete
    methods: [DELETE]


#heating
heating:
    path: /heating
    controller: App\Controller\HeatingController::index
    methods: [GET]


#lucky
lucky_number:
    path: /lucky_number
    controller: App\Controller\LuckyController::lucky_number
    methods: [GET]

lucky_generatePositive:
    path: /lucky_generatePositive
    controller: App\Controller\LuckyController::generatePositive
    methods: [GET]


#ship
ship_index:
    path: /ship
    controller: App\Controller\ShipController::index
    methods: [GET]

ship_choose:
    path: /ship/choose/{id}
    controller: App\Controller\ShipController::choose
    methods: [GET]

user_ship_edit:
    path: /user/ship/edit
    controller: App\Controller\ShipController::edit
    methods: [GET, POST]


#user
user_ship:
    path: /user/ship/
    controller: App\Controller\UserController::ship
    methods: [GET]

user:
    path: /user
    controller: App\Controller\UserController::index
    methods: [GET]

#planet
planet_index:
    path: /planet
    controller: App\Controller\PlanetController::index
    methods: [GET]


planet_create:
    path: /planet/new
    controller: App\Controller\PlanetController::new
    methods: [GET, POST]


planet_edit:
    path: /planet/edit/{id}
    controller: App\Controller\PlanetController::show
    methods: [GET, POST]


planet_delete:
    path: /planet/delete/{id}
    controller: App\Controller\PlanetController::delete

planets_list:
    path: /planets_list
    controller: App\Controller\PlanetController::list
    methods: [GET]


javascript_index:
    path: /javascript
    controller: App\Controller\JavaScriptController::index
    methods: [GET]